services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10

  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1
      LABEL_con1: "Convergence"
      SERVER_con1: db
      USER_con1: ${DATABASE_USERNAME}
      PASSWORD_con1: ${DATABASE_PASSWORD}
      PORT_con1: ${DATABASE_PORT}
      ENGINE_con1: postgres@dbgate-plugin-postgres
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
  dbgate-data:
    driver: local
