# fly.toml app configuration file generated for convergence-games-dev on 2026-04-19T21:02:27+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'convergence-games-dev'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[env]
  BASE_DOMAIN = 'https://dev.convergence.waikatorpg.co.nz'
  BASE_REDIRECT_URI = 'https://dev.convergence.waikatorpg.co.nz'
  DATABASE_PORT = '5432'
  DEBUG = 'true'
  DEFAULT_EVENT_ID = '2'
  ENVIRONMENT = 'development'
  FLAG_PLANNER = 'true'
  FLAG_PREFERENCES = 'true'
  IMAGE_STORAGE_ACCOUNT_NAME = 'stconvergencedev'
  IMAGE_STORAGE_CONTAINER_NAME = 'uploads'
  IMAGE_STORAGE_MODE = 'blob'
  IMAGE_STORAGE_PRE_CACHE_SIZES = '[300]'
  SENTRY_PROFILES_SAMPLE_RATE = '1.0'
  SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE = '1.0'
  SENTRY_REPLAYS_SESSION_SAMPLE_RATE = '1.0'
  SENTRY_TRACES_SAMPLE_RATE = '1.0'
  SITE_TITLE = 'Convergence 2026'
  WEB_CONCURRENCY = '2'
  # AZURE_CLIENT_ID = 'SECRET'
  # AZURE_CLIENT_SECRET = 'SECRET'
  # AZURE_TENANT_ID = 'SECRET'
  # BREVO_API_KEY = 'SECRET'
  # DATABASE_HOST = 'SECRET'
  # DATABASE_NAME = 'SECRET'
  # DATABASE_PASSWORD = 'SECRET'
  # DATABASE_USERNAME = 'SECRET'
  # DISCORD_CLIENT_ID = 'SECRET'
  # DISCORD_CLIENT_SECRET = 'SECRET'
  # GOOGLE_CLIENT_ID = 'SECRET'
  # GOOGLE_CLIENT_SECRET = 'SECRET'
  # SENTRY_DSN = 'SECRET'
  # SENTRY_LOADER_SRC = 'SECRET'
  # SIGNING_KEY = 'SECRET'
  # TOKEN_SECRET = 'SECRET'
