services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: MIGRATION_USER
      POSTGRES_PASSWORD: MIGRATION_PASSWORD
      POSTGRES_DB: convergence
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U MIGRATION_USER -d convergence"]
      interval: 1s
      timeout: 5s
      retries: 10

  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1
      LABEL_con1: "Convergence"
      SERVER_con1: db
      USER_con1: MIGRATION_USER
      PASSWORD_con1: MIGRATION_PASSWORD
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
      PORT: 3002
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
  dbgate-data:
    driver: local
