"""Add user_game_played table

Revision ID: d3384dbfde28
Revises: a8b29793de9a
Create Date: 2025-09-08 19:46:05.711268

"""
# pyright: reportUnusedCallResult=false

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "d3384dbfde28"
down_revision = "a8b29793de9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_game_played",
        sa.Column("allow_play_again", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("game_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False, autoincrement=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("updated_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name=op.f("fk_user_game_played_created_by_user")),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], name=op.f("fk_user_game_played_game_id_game")),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name=op.f("fk_user_game_played_updated_by_user")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_game_played_user_id_user")),
        sa.PrimaryKeyConstraint("user_id", "game_id", "id", name=op.f("pk_user_game_played")),
        sa.UniqueConstraint("user_id", "game_id", name=op.f("uq_user_game_played_user_id")),
    )
    with op.batch_alter_table("user_game_played", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_game_played_allow_play_again"), ["allow_play_again"], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_game_played", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_game_played_allow_play_again"))

    op.drop_table("user_game_played")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
