"""Add frozen_at_time_slot_id to user game preference

Revision ID: bb8d9e0cab15
Revises: a9734f9abf91
Create Date: 2025-09-07 16:38:27.079185

"""
# pyright: reportUnusedCallResult=false

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "bb8d9e0cab15"
down_revision = "a9734f9abf91"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_game_preference", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("frozen_at_time_slot_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True)
        )
        batch_op.drop_constraint("uq_user_game_preference_game_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_game_preference_game_id"), ["game_id", "user_id", "frozen_at_time_slot_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_game_preference_frozen_at_time_slot_id"), ["frozen_at_time_slot_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_game_preference_frozen_at_time_slot_id_time_slot"),
            "time_slot",
            ["frozen_at_time_slot_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_game_preference", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_game_preference_frozen_at_time_slot_id_time_slot"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_user_game_preference_frozen_at_time_slot_id"))
        batch_op.drop_constraint(batch_op.f("uq_user_game_preference_game_id"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_user_game_preference_game_id", ["game_id", "user_id"], postgresql_nulls_not_distinct=False
        )
        batch_op.drop_column("frozen_at_time_slot_id")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
