"""Add allocation table

Revision ID: a9734f9abf91
Revises: 2d695ef1feed
Create Date: 2025-09-07 16:05:08.022786

"""
# pyright: reportUnusedCallResult=false

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "a9734f9abf91"
down_revision = "2d695ef1feed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation",
        sa.Column("committed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("party_leader_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("session_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False, autoincrement=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("updated_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name=op.f("fk_allocation_created_by_user")),
        sa.ForeignKeyConstraint(["party_leader_id"], ["user.id"], name=op.f("fk_allocation_party_leader_id_user")),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name=op.f("fk_allocation_session_id_session"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name=op.f("fk_allocation_updated_by_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation")),
        sa.UniqueConstraint("party_leader_id", "session_id", "committed", name=op.f("uq_allocation_party_leader_id")),
    )
    with op.batch_alter_table("allocation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_allocation_committed"), ["committed"], unique=False)
        batch_op.create_index(batch_op.f("ix_allocation_party_leader_id"), ["party_leader_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_allocation_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allocation_session_id"))
        batch_op.drop_index(batch_op.f("ix_allocation_party_leader_id"))
        batch_op.drop_index(batch_op.f("ix_allocation_committed"))

    op.drop_table("allocation")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
