"""add event time span fields

Revision ID: 849b06f7ac73
Revises: 9fe4b5706234
Create Date: 2026-05-06 18:55:59.186353

"""
# pyright: reportUnusedCallResult=false

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "849b06f7ac73"
down_revision = "9fe4b5706234"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("submissions_open_at", sa.DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("submissions_close_at", sa.DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("editing_close_at", sa.DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("preferences_open_at", sa.DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("planner_open_at", sa.DateTimeUTC(timezone=True), nullable=True))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("planner_open_at")
        batch_op.drop_column("preferences_open_at")
        batch_op.drop_column("editing_close_at")
        batch_op.drop_column("submissions_close_at")
        batch_op.drop_column("submissions_open_at")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
