"""Add table size to table

Revision ID: 634c88dabfb5
Revises: 75fd2d155fe3
Create Date: 2025-07-31 22:05:02.252930

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    PasswordHash,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "634c88dabfb5"
down_revision = "75fd2d155fe3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("table", schema=None) as batch_op:
        sa.Enum("SMALL", "LARGE", name="tablesize").create(op.get_bind())
        batch_op.add_column(
            sa.Column(
                "size",
                postgresql.ENUM("SMALL", "LARGE", name="tablesize", create_type=False),
                server_default="SMALL",
                nullable=False,
            )
        )
        batch_op.create_index(batch_op.f("ix_table_size"), ["size"], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("table", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_table_size"))
        batch_op.drop_column("size")
        sa.Enum("SMALL", "LARGE", name="tablesize").drop(op.get_bind())

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
